django/april_test/home/workspace/April/April/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

django/april_test/home/workspace/April/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', views.logout, name='logout'),
]

django/april_test/home/workspace/April/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.list, name='list'),
    path('create/', views.create, name='create'),
    path('like/<int:post_id>/', views.like, name='like'),
]

django/april_test/home/workspace/April/accounts/models.py
from django.db import models

# Create your models here.

django/april_test/home/workspace/April/posts/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Post(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

django/april_test/home/workspace/April/accounts/forms.py
from django import forms
from django.contrib.auth.models import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCustomCreationForm(forms.UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = '__all__'

django/april_test/home/workspace/April/posts/forms.py
from django import forms
from .models import Post

# Q2-1 문제의 답안 코드를 아래에 작성하세요.
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content']

django/april_test/home/workspace/April/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

def signup(request):
    # Q1-1, Q1-2 문제의 답안 코드를 pass를 지우고 아래에 작성하세요.
    user = get_user_model()
    if request.method == 'POST':
        user_form = UserCreationForm(request.POST)
        user = user_form.save(commit=False)
        user.save()
        return redirect('posts:list')
    else:
        user_form = UserCreationForm()
        context = {'form':user_form}
    return render(request, 'accounts/signup.html', context)

# 주의
# 로그인 관련 함수가 보이지 않을 뿐 정상 로그인 됩니다.
# /accounts/login URL을 통해 로그인 됩니다.

def logout(request):
    auth_logout(request)
    return redirect("posts:list")

django/april_test/home/workspace/April/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def list(request):
    posts = Post.objects.all()
    context = {'posts':posts}
    return render(request, 'posts/list.html', context)

@login_required
def create(request):
    # Q2-2, Q2-3 문제의 답안 코드를 pass를 지우고 아래에 작성하세요.
    post = Post()
    if request.method=='POST':
        if request.user.is_authenticated:
            post_form = PostForm(request.POST)
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()
        return redirect('posts:list')
    else:
        post_form = PostForm()
        context = {'form':post_form}
        return render(request, 'posts/form.html', context)

@login_required
def like(request, post_id):
    # Q3-3 문제의 답안 코드를 pass를 지우고 아래에 작성하세요.
    post = Post.objects.get(id=post_id)
    user = request.user
    if user in post.like_users.all():
        post.like_users.remove(user)
    else:
        post.like_users.add(user)
    if user in post.like_users:
        tmp = 0
    else:
        tmp = 1
    context = {'tmp':tmp}
    return redirect('posts:list', context)

django/april_test/home/workspace/April/April/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
        <a href="{% url 'posts:create' %}">글쓰기</a>
        <a href="{% url 'accounts:logout' %}">로그아웃</a>
    {% else %}
        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

django/april_test/home/workspace/April/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
    <h1>로그인</h1>
    <form method="POST">
        {% csrf_token %} 
        {{form}}
        <input type="submit">
    </form>
{% endblock %}

django/april_test/home/workspace/April/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block body %}
    <h1>회원가입</h1>
    <form method="POST">
        {% csrf_token %} 
        {{form}}
        <input type="submit">
    </form>
{% endblock %}