django/django-intro/home/workspace/movie_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.list, name='list'),
    path('<int:user_pk>/', views.detail, name='detail'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

django/django-intro/home/workspace/movie_pjt/movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

django/django-intro/home/workspace/movie_pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.list, name='list'),
    path('<int:movie_pk>', views.detail, name='detail'),
    path('<int:movie_pk>/scores/new', views.score_create, name='score_create'),
    path('<int:movie_pk>/scores/<int:score_pk>/delete', views.score_delete, name='score_delete'),
]

django/django-intro/home/workspace/movie_pjt/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

django/django-intro/home/workspace/movie_pjt/movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=20)
        
class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    score_users = models.ManyToManyField(
                                    settings.AUTH_USER_MODEL, 
                                    through='Score', 
                                    related_name='score_movies'
                                    )

class Score(models.Model):
    content = models.CharField(max_length=140)
    value = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

django/django-intro/home/workspace/movie_pjt/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email',)

django/django-intro/home/workspace/movie_pjt/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from .models import User
from movies.models import Score
from .forms import UserCustomCreationForm

# Create your views here.
def list(request):
    users = User.objects.all()
    context = {'users':users}
    return render(request, 'accounts/list.html', context)
    
from django.db.models import Prefetch
def detail(request, user_pk):
    user = User.objects.get(pk=user_pk)
    scores = user.score_set.all()
    score_one = Score.objects.order_by('-value')[0]
    # User = get_user_model()
    # user = get_object_or_404(User.objects.annotate(followers_count=Count('followers'),followings_count=Count('followings')), pk=user_pk)
    # followings = user.followings.prefetch_related(Prefetch('score_set',query_set=Score.objects.select_related('movie').order_by('value'),to_attr='score_set_value_order'))
    followings = user.followings.all()
    score_following = []
    for following in followings:
        if Score.objects.filter(user=following):
            score_following.append(Score.objects.filter(user=following).order_by('-value')[0])
    context = {'user_info':user, 'scores':scores, 'score_one':score_one, 'score_following':score_following}
    return render(request, 'accounts/detail.html', context)
    
@require_http_methods(["GET", "POST"])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        user_form = UserCustomCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            auth_login(request, user)
            return redirect('movies:list')
    else:
        user_form = UserCustomCreationForm()
    context = {'form': user_form}
    return render(request, 'accounts/forms.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect('movies:list')
    else:
        login_form = AuthenticationForm()
    context = {'form': login_form}
    return render(request, 'accounts/forms.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:list')
    
@login_required    
def follow(request, user_pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=user_pk)
    if request.user in user.followers.all():
        user.followers.remove(request.user)
    else:
        user.followers.add(request.user)
        
    return redirect('accounts:detail', user_pk)

django/django-intro/home/workspace/movie_pjt/movies/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Genre, Movie, Score
# Create your views here.
def list(request):
    movies = Movie.objects.all()
    context = {'movies':movies}
    return render(request, 'movies/list.html', context)
    
def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    scores = movie.score_set.all()
    context = {'movie':movie, 'scores':scores}
    return render(request, 'movies/detail.html', context)

@login_required
def score_create(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    score = Score()
    score.content = request.POST.get('content')
    score.value = request.POST.get('value')
    score.movie = movie
    score.user = request.user
    score.save()
    return redirect('movies:detail', movie_pk)
    
def score_delete(request, movie_pk, score_pk):
    if request.method == "POST":
        score = Score.objects.get(pk=score_pk)
        score.delete()
    return redirect('movies:detail', movie_pk)

django/django-intro/home/workspace/movie_pjt/movie_pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'movies:list' %}">영화보기</a>
    <a href="{% url 'accounts:list' %}">유저보기</a>
    {% if user.is_authenticated %}
        <p>{{ user.username }}</p>
        <a href="{% url 'accounts:detail' user.pk %}">유저정보</a>
        <a href="{% url 'accounts:logout' %}">로그아웃</a>
        {% else %}
        <a href="{% url 'accounts:signup' %}">회원가입</a>
        <a href="{% url 'accounts:login' %}">로그인</a>
    {% endif %}
    <hr> 
    {% block body %}
    {% endblock %}
</body>
</html>

django/django-intro/home/workspace/movie_pjt/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block body %}
    <p>{{ movie.title }}</p>
    <p>{{ movie.audience }}</p>
    <img src='{{ movie.poster_url }}'>
    <p>{{ movie.description }}</p>
    <p>{{ movie.genre.name }}</p>
    <p>댓글 작성 {{ scores.count }}</p>
    <form action="{% url 'movies:score_create' movie.pk %}" method="POST">
        {% csrf_token %}
        내용 : <input type="text" name="content"><br>
        점수 : <input type="integer" name="value"><br>
        <input type="submit">
    </form>
    <hr>
    {% for score in scores %}
        <li>{{ score.user }}, {{ score.value }}점: {{ score.content }}
            {% if score.user == user %}
            <form action="{% url 'movies:score_delete' movie.pk score.pk %}" method="POST" style="display: inline" onsubmit="return confirm('삭제할거야?')">
                {% csrf_token %}
                <input type="submit" value="삭제">
            </form>
            {% endif %}
        </li>
    {% endfor %}
{% endblock %}

django/django-intro/home/workspace/movie_pjt/movies/templates/movies/list.html
{% extends 'base.html' %}
{% block body %}
<h1>Movies List</h1>
{% for movie in movies %}
    <a href='{% url "movies:detail" movie.pk %}'><img src='{{ movie.poster_url }}'%}></a><br>
{% endfor %}
{% endblock %}