django/django-intro/home/workspace/instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/django-intro/home/workspace/instagram/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('', views.list, name='list'),
    path('make/', views.make, name='make'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete', views.delete, name='delete'),
    path('<int:post_pk>/edit', views.edit, name='edit'),
    path('<int:post_pk>/comment_create', views.comment_create, name='comment_create'),
    path('<int:post_pk>/<int:comment_pk>/comments_delete', views.comments_delete, name='comments_delete'),
    path('<int:post_pk>/like', views.like, name='like'),
    path('hashtags/<int:hashtag_pk>', views.hashtag, name='hashtag'),
]

django/django-intro/home/workspace/instagram/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
# Create your models here.

class Hashtag(models.Model):
    content = models.TextField(unique=True)

class Post(models.Model):
    content = models.TextField()
    # image = models.ImageField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_posts')
    hashtags = models.ManyToManyField(Hashtag, blank=True, related_name='posts')
    
    @property
    def like_count(self):
        return self.liked_users.count()
    
    def __str__(self):
        return f'Post : {self.pk} '
        
    def get_absolute_url(self):
        return reverse('posts:detail', args=[self.pk])
            
class Image(models.Model):
    file = models.ImageField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
        
class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    def __str__(self):
        return self.content

django/django-intro/home/workspace/instagram/posts/forms.py
from django import forms
from .models import Post, Image, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content',]

        
class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        exclude = ('post', )
        widgets = {
            'file': forms.FileInput(attrs={'multiple':True}),
        }
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

django/django-intro/home/workspace/instagram/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db.models import Q 
from .models import Post, Image, Comment, Hashtag
from .forms import PostForm, ImageForm, CommentForm
from django.http import JsonResponse

# Create your views here.
@login_required
def list(request):
    # images = Image.objects.all()
    posts = Post.objects.filter(Q(user__in=request.user.followings.values('id')) | Q(user=request.user.id)).order_by('-pk')
    context = {'posts': posts}
    # context = {'images':images}
    
# {% for image in images %}
#     <img src="{{ image.file.url }}" class="card-img-top" alt="...">
# {% endfor %}
    return render(request, 'posts/list.html', context)

@login_required    
def make(request):
    if request.method=='POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()
            files = request.FILES.getlist('file')
            for file in files:
                request.FILES['file'] = file
                image_form = ImageForm(files=request.FILES)
                if image_form.is_valid():
                    image = image_form.save(commit=False)
                    image.post = post
                    image.save()
            # 1. 내용을 공백 단위로 쪼개서 반복문을 돌리면
            for word in post.content.split():
            # 1-1. #이 가장 앞에 있으면,
                if word.startswith('#'):
            # 1-1-1. 해시태크에 저장이 되어 있으면, 가져와서 추가
            # 1-1-2. 저장이 안되어 있으면, 만들어서 추가
                    hashtag, is_created = Hashtag.objects.get_or_create(content=word)
                    post.hashtags.add(hashtag)
                    # 만들어지면 : (hashtag object, True)
                    # 가져와지면 : (hashtag object, False)
            
            return redirect(post)
    else:
        post_form = PostForm()
        image_form = ImageForm()
    context = {'post_form' : post_form, 'image_form': image_form}
    return render(request, 'posts/make.html', context)
    
def detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comments = post.comment_set.all()
    hashtags = post.hashtags.all()
    context = {'post': post, 'comments':comments, 'hashtags':hashtags, 'comment_form': CommentForm()}
    return render(request, 'posts/detail.html', context)

@login_required
def delete(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    post.delete()
    return redirect('posts:list')
    
@login_required
def edit(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        post_form = PostForm(request.POST, instance=post)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.save()
            post.hashtags.clear()
            for word in post.content.split():
                if word.startsweith('#'):
                    hashtag, is_created = Hashtag.objects.get_or_create(content=word)
                    post.hashtags.add(hashtag)
            return redirect(post)
    else:
        post_form = PostForm(instance=post)
    context = {'post':post, 'post_form':post_form}
    return render(request, 'posts/make.html', context)
    
def comment_create(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.post = post
        comment.user = request.user
        comment.save()
        data = {'username': comment.user.username, 
                'content': comment.content,
                'postPk': comment.post.pk,
                'commentPk': comment.pk
                }
        return JsonResponse(data)
    
def comments_delete(request, post_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('posts:detail', post_pk)
    
def like(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    User = get_user_model()
    user = request.user
    user = user
    # user가 지금 해당 게시글에 좋아요를 한적이 있는지?
    # if user in post.liked_users.all():
    #     post.liked_users.remove(user)
    # else:
    #     post.liked_users.add(user)
    if post.liked_users.filter(pk=user.id).exists():
        post.liked_users.remove(user)
        is_like = False
    else:
        post.liked_users.add(user)
        is_like = True
    # return redirect('posts:detail', post_pk)
    return JsonResponse({'is_like': is_like, 'count': post.liked_users.count()})
    
def hashtag(request, hashtag_pk):
    hashtag = get_object_or_404(Hashtag, pk=hashtag_pk)
    posts = hashtag.posts.all()
    context = {'posts':posts, 'hashtag':hashtag}
    return render(request, 'posts/hashtag.html', context)

django/django-intro/home/workspace/instagram/posts/templates/posts/detail.html
{% extends 'base.html' %}
{% block body %}
    <p>{{ post.pk }}</p>
    <!--<p>{{ post.content }}</p>-->
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            {% for image in post.image_set.all %}
            <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                <img src="{{ image.file.url }}" class="d-block" width='600px' height='600px'>
            </div>
            {% endfor %}
        </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    {% load hashtag_link %}
    <p>{{ post|hashtag_link|safe }}</p>
    {% for hashtag in hashtags %}
        <a href="{% url 'posts:hashtag' hashtag.pk %}">{{ hashtag.content }} </a>
    {% endfor %}
    <br>
    <i data-id='{{post.pk}}' class='{% if user in post.liked_users.all %} fas {% else %} far {% endif %} fa-heart fa-2x like-button' style='color:hotpink;'></i></a>
    <span><span id='like-count-{{post.pk}}'>{{ post.like_count }}</span>명</span>
    <a href='{% url "posts:edit" post.pk %}'>수정</a>
    <a href='{% url "posts:delete" post.pk %}'>삭제</a>
    <hr>
    <p>댓글 작성 {{ comments.count }}</p>
    <!--<form action="{% url 'posts:comment_create' post.pk %}" method="POST">-->
    <!--    {% csrf_token %}-->
    <!--    <input type="text" name="content">-->
    <!--    <input type="submit">-->
    <!--</form>-->
    <form action="{% url 'posts:comment_create' post.pk %}" class="comment-form" method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button type="submit" class="btn btn-primary">댓글 작성</button>
    </form>
        <div id="comment-{{ post.pk }}">
          {% for comment in post.comment_set.all %}
            <p>{{ comment.user.username}} : {{ comment.content }} 
              <a href="{% url 'posts:comments_delete' post.pk comment.pk %}">[x]</a>
            </p>
          {% endfor %}
{% endblock %}


{% block script %}
<script>
    const likeButton = document.querySelector('.like-button')
    // 이벤트가 발생하면
    likeButton.addEventListener('click', function(e) {
        const postId = e.target.dataset.id
        // 장고 서버로 요청을 보내고
        axios.get(`/posts/${postId}/like`)
        // 성공하면, response에 장고에서 보낸 내용이 담겨있고, (JSON)
        .then(function(response) {
            // 실제 모습처럼 그린다. 새롭게(실제 로딩되었을 때의 화면과 동일)
            const likeCount = document.querySelector(`#like-count-${postId}`)
            likeCount.innerText = response.data.count
            console.log(e.target)
            if (response.data.is_like) {
                e.target.classList.remove('far')
                e.target.classList.add('fas')
            } else {
                e.target.classList.remove('fas')
                e.target.classList.add('far')
            }
        })
    })
    const commentForms = document.querySelectorAll('.comment-form')
        commentForms.forEach(function(form) {
            form.addEventListener('submit', function(event){
            event.preventDefault()
            axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'
            // csrf_token을 위한 것
            axios.defaults.xsrfCookieName = 'csrftoken'
            axios.defaults.xsrfHeaderName = 'X-CSRFToken' 
            const url = event.target.getAttribute('action')
            const data = new FormData(event.target)
            axios.post(url, data)
                .then(function(response) {
                    console.log(response)
                    event.target.reset()
                    const content = `<p>${response.data.username} : ${response.data.content} 
                    <a href="/posts/${response.data.postPk}/${response.data.commentPk}/delete">[x]</a>
                    </p>`
                    const commentDiv = document.querySelector(`#comment-${response.data.postPk}`)
                    commentDiv.insertAdjacentHTML('beforeend', content)
                })
        })
    })
</script>
{% endblock %}

django/django-intro/home/workspace/instagram/posts/templates/posts/hashtag.html
{% extends 'base.html' %}
{% block body %}
    <h1>{{ hashtag.content }}</h1>
    {% for post in posts %}
        <a href="{% url 'posts:detail' post.pk %}">
            <img src="{{ post.image_set.first.file.url }}" class="d-block" width='300px' height='300px'>
    {% endfor %}
{% endblock %}

django/django-intro/home/workspace/instagram/posts/templates/posts/list.html
{% extends 'base.html' %}
{% block body %}
<h1>리스트페이지</h1>
<div class="row">
{% for post in posts %}
    <div class="card col-4" style="width: 18rem; height: 30rem; border-style:none">
        <a href='{% url "posts:detail" post.pk %}'>
            <img src="{{ post.image_set.first.file.url }}" class="card-img-top" alt="post.content" style='height: 18rem'>
            <div class="card-body">
                <h5 class="card-title">{{ post.content }}</h5>
            </div>
        </a>
    </div>
{% endfor %}
</div>
{% endblock %}

django/django-intro/home/workspace/instagram/posts/templates/posts/make.html
{% extends 'base.html' %}
{% block body %}
<form method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    {{ post_form.as_p }}
    {{ image_form.as_p }}
    <!--image : <input type='file' name='image' accept='image/*'><br>-->
    <input type='submit'>
</form>
{% endblock %}