django/django-intro/home/workspace/instagram/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
    path('fake/', views.fake, name='fake'),
    path('visit/', views.visit, name='visit'),
    path('profile/update/', views.profile_update, name='profile_update'),
    path('profile/', views.profile, name='profile'),
    path('<int:user_pk>/', views.detail, name='detail'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('search/', views.search, name='search'),
    path('', views.userlist, name='list'),
]

django/django-intro/home/workspace/instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/django-intro/home/workspace/instagram/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('', views.list, name='list'),
    path('make/', views.make, name='make'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete', views.delete, name='delete'),
    path('<int:post_pk>/edit', views.edit, name='edit'),
    path('<int:post_pk>/comment_create', views.comment_create, name='comment_create'),
    path('<int:post_pk>/<int:comment_pk>/comments_delete', views.comments_delete, name='comments_delete'),
    path('<int:post_pk>/like', views.like, name='like'),
    path('hashtags/<int:hashtag_pk>', views.hashtag, name='hashtag'),
]

django/django-intro/home/workspace/instagram/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=30)
    introduction = models.TextField()
    image = ProcessedImageField(
                    processors=[ResizeToFill(300,300)],
                    format='JPEG',
                    options={'quality': 80},
                )

django/django-intro/home/workspace/instagram/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.conf import settings
from .models import Profile

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'email',)
        
class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name',)
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user', )

django/django-intro/home/workspace/instagram/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from .models import Profile
from .forms import UserCustomChangeForm, UserCustomCreationForm, ProfileForm
from django.http import JsonResponse, HttpResponseBadRequest
# Create your views here.
@require_http_methods(['GET','POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:list')
    if request.method == 'POST':
        user_form = UserCustomCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            # Profile.objects.create(user=user)
            auth_login(request, user)
            return redirect('accounts:profile_update')
    else:
        user_form = UserCustomCreationForm()
    context = {'user_form': user_form}
    return render(request, 'accounts/signup.html', context)

# def signup(request):
#     return redirect('http://django-intro-thjeong2230.c9users.io:8080/posts/')
    
def login(request):
    if request.user.is_authenticated:
        return redirect('posts:list')
    if request.method== 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect(request.GET.get('next') or 'posts:list')
    else:
        login_form = AuthenticationForm()
    context = {'login_form': AuthenticationForm()}
    return render(request, 'accounts/login.html', context)
    
@login_required
def logout(request):
    auth_logout(request)
    return redirect('posts:list')

@login_required
def delete(request):
    request.user.delete()
    return redirect('posts:list')
    
@require_http_methods(["GET", "POST"])
def update(request):
    if request.method == "POST":
        user_form = UserCustomChangeForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            return redirect('posts:list')
    else:
        user_form = UserCustomChangeForm(instance=request.user)
    context = {'user_form': user_form}
    return render(request, 'accounts/update.html', context)
    
@login_required
def password(request):
    if request.method == 'POST':
        user_form = PasswordChangeForm(request.user, request.POST) # 순서 주의!
        if user_form.is_valid():
            user = user_form.save()
            update_session_auth_hash(request, user)
            return redirect('posts:list')
    else:
        user_form = PasswordChangeForm(request.user) # instance 아님 주의!
    context = {'user_form': user_form}
    return render(request, 'accounts/update.html', context)
    
def fake(request):
    return render(request, 'accounts/fake.html')
    
def visit(request):
    return render(request, 'accounts/visit.html')

@login_required
def profile_update(request):
    try:
        request.user.profile
    except:
        Profile.objects.create(user=request.user)
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('accounts:profile')
    profile_form = ProfileForm(instance=request.user.profile)
    context = {'profile_form':profile_form}
    return render(request, 'accounts/profile_update.html', context)

@login_required    
def profile(request):
    return render(request, 'accounts/profile.html')
    
@login_required
def detail(request, user_pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=user_pk)
    context = {'user_info':user}
    return render(request, 'accounts/detail.html', context)

@login_required    
def follow(request, user_pk):
    if request.is_ajax():
        User = get_user_model()
        user = get_object_or_404(User, pk=user_pk)
        # if request.user in user.followers.all():
        #     user.followers.remove(request.user)
        # else:
        #     user.followers.add(request.user)
        if request.user in user.followers.all():
            user.followers.remove(request.user)
            is_follow = False
        else:
            user.followers.add(request.user)
            is_follow = True
        # return redirect('accounts:detail', user_pk)
        return JsonResponse({'is_follow':is_follow, 'followercount':user.followers.count(), 'followingcount':user.followings.count() })
    else:
        return HttpResponseBadRequest
    
def search(request):
    # 1. 내가 만들어놓은 모델
    # 2. variable routing (X)
    # 3. form (O)
    username = request.GET.get('username')
    User = get_user_model()
    user = User.objects.filter(username=username).first()
    if not user:
        return redirect('posts:list')
    return redirect('accounts:detail', user.pk)
    
def userlist(request):
    User = get_user_model()
    users = User.objects.all()
    context = {'users':users}
    return render(request, 'accounts/list.html', context)

django/django-intro/home/workspace/instagram/accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block body %}
    <p>{{ user_info.username }}</p>
    <div class='follow-count'>
        <p>팔로잉 : {{ user_info.followings.all.count }}</p>
        <p>팔로워 : {{ user_info.followers.all.count }}</p>
    </div>
    {% if user != user_info %}
        {% if user in user_info.followers.all %}
            <a id='follow-button' href='{% url "accounts:follow" user_info.pk%}'>팔로우취소</a>
        {% else %}
            <a id='follow-button' href='{% url "accounts:follow" user_info.pk%}'>팔로우</a>
        {% endif %}
    {% endif %}
{% endblock %}


{% block script %}
<script>
    if (document.querySelector('#follow-button')) {
    const followButton = document.querySelector('#follow-button')
    followButton.addEventListener('click', function(e) {
        e.preventDefault()
        const url = e.target.getAttribute('href')
        // is_ajax() True 를 위한 것
        axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'
        // csrf_token을 위한 것
        axios.defaults.xsrfCookieName = 'csrftoken'
        axios.defaults.xsrfHeaderName = 'X-CSRFToken'
        // csrftoken을 Header에 담을 때 X-CSRFToken 으로 보내라고 Django에 설정되어 있음.
        axios.post(url)
            .then(function(response) {
                const followCountDiv = document.querySelector('.follow-count')
                followCountDiv.children[0].innerText = `팔로잉 : ${response.data.followingcount}`
                followCountDiv.children[1].innerText = `팔로워 : ${response.data.followercount}`
                e.target.innerText = response.data.is_follow ? '팔로우취소': '팔로우'
            })
    })
    }
</script>
{% endblock %}

django/django-intro/home/workspace/instagram/accounts/templates/accounts/list.html
{% extends 'base.html' %}
{% block body %}
<h1>리스트페이지</h1>
<h3>{{ request.user }}</h3>
{% for user in users %}
    <p>{{ user.id }}.<a href='{% url "accounts:detail" user.pk %}'>{{ user.username }}</a></p>
{% endfor %}
{% endblock %}

django/django-intro/home/workspace/instagram/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block body %}
{% load socialaccount %}
<form method="POST">
    {% csrf_token %}
    {{ login_form.as_p }}
    <input type="submit" value="로그인">
</form>
<a href="{% provider_login_url 'kakao' method='oauth2' %}">카카오 로그인</a>
{% endblock %}

django/django-intro/home/workspace/instagram/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block body %}
    <p>{{ user.username }}</p>
    <p>{{ user.profile.nickname }}</p>
    <p>{{ user.profile.introduction }}</p>
    <img src='{{ user.profile.image.url }}' class='rounded-circle'><br>
    <a href='{% url "accounts:profile_update" %}'>수정</a>
{% endblock %}

django/django-intro/home/workspace/instagram/accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% block body %}
    <form method="POST" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ profile_form.as_p }}
        <button type='submit' class='btn btn-warning'>완료</button>
    </form>
{% endblock %}

django/django-intro/home/workspace/instagram/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    {{ user_form.as_p }}
    <input type="submit" value="회원가입 신청">
</form>
{% endblock %}

django/django-intro/home/workspace/instagram/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    {{ user_form.as_p }}
    <input type="submit" value="프로필 수정">
</form>
{% endblock %}

django/django-intro/home/workspace/instagram/accounts/templates/accounts/visit.html
{% extends 'base.html' %}
{% block body %}
<h1>
<a href='http://django-intro-takikim.c9users.io:8080/posts/'>타키</a><br>
<a href='http://django-intro-yooco.c9users.io:8080/posts/'>유중위</a><br>
<a href='http://django-intro-mingury83.c9users.io:8080/posts/'>minz</a><br>
<a href='http://django-intro-ddongss.c9users.io:8080/posts/'>셀럽</a><br>
<a href='http://django-intro-goodminkyo.c9users.io:8080/posts/'>갓민교</a><br>
<a href='http://django-intro-pigeonking.c9users.io:8080/posts/'>구구</a><br>
<a href='http://django-intro-dpwl7484.c9users.io:8080/posts'>dPwl</a><br>
<a href='http://django-intro-sweetrain.c9users.io:8080/posts/'>트와이스</a><br>
<a href='http://django-intro-thjeong2230.c9users.io:8080/posts/'>쉬는시간</a><br>
<a href='http://django-intro-psmiswell.c9users.io:8080/posts/'>박성민이즈웰</a><br>
<a href='http://django-intro-yoonwoo.c9users.io:8080/posts/'>윤우네</a><br>
<a href='http://django-intro-injeong.c9users.io:8080/posts/'>인정?</a><br>
<a href='http://django-intro-dmlim.c9users.io:8080/posts/'>Pokemon</a><br>
<a href='http://django-intro-ksinuk1.c9users.io:8080/posts/'>행복한신욱이네</a><br>
<a href='http://django-intro-leeiopd.c9users.io:8080/posts/'>호호호주호</a><br>
<a href='http://django-intro-dohbam.c9users.io:8080/posts/'>갓희윤</a><br>
<a href='http://django-intro-opalcat01.c9users.io:8080/posts/'>노블레스</a><br>
<a href='http://django-intro-yeojineee.c9users.io:8080/posts/'>황여사님</a><br>
<a href='http://django-intro-tmair2.c9users.io:8080/posts/'>짠!</a><br>
<a href='http://django-intro-frtt0608.c9users.io:8080/posts/'>예쁜남자</a><br>
<a href='http://django-intro-rlatmf2147.c9users.io:8080/posts/'>반장님~</a><br>
<a href='http://django-intro-manuck.c9users.io:8080/posts/'>씅마이</a><br>
</h1>
{% endblock %}